### ISSUE TITLE
Requires UART?

### ISSUE THREAD

**Issue by rodneygp** [Brokly/bl0942#1]
Hi!

My BL0937 seems to be connected directly to my bk7231t. That is, its SEL, CF and CF1 are connected to GPIO24, GPIO9 and GPIO8 of my board.

Do I understand it right, that I can't use this component in such a case? I am currently using hlw8012 with option "model: BL0937".

Regards, Rodion

**Comment by Brokly** [comment]
Unfortunately, I don't understand the question. This is a standard connection for the driver. Are you having problems using UART on these MCU outputs?
